// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    /** The page component is a server function; its `$component` is delivered eagerly. */
    server?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(mail)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(mail)")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/index")>;
    },
    {
      path: "/(mail)/inbox/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(mail)/inbox/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(mail)/inbox/index")>;
    },
    {
      path: "/(mail)/inbox/:threadId";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(mail)/inbox/[threadId]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(mail)/inbox/[threadId]")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/index")>;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/";
      id: "/(mail)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(mail)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/inbox/";
          id: "/inbox/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(mail)/inbox/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(mail)/inbox/index")>;
          children?: undefined;
        },
        {
          path: "/inbox/:threadId";
          id: "/inbox/:threadId";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(mail)/inbox/[threadId]")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(mail)/inbox/[threadId]")>;
          children?: undefined;
        }
      ];
    }
  ];
}
